GXX = g++
CFLAGS = -g -Wall

problem6: 
	$(GXX) $(CFLAGS) problem6.cpp llistint.cpp -o problem6
problem7: 
	$(GXX) $(CFLAGS) problem7.cpp llistint.cpp -o problem7
clean:
	rm problem7
	rm problem6
	rm problem5